[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "dunya-jewellery-frontend"

[services.variables]
NODE_VERSION = "18"

[[services.ports]]
port = 3000
handler = "http"

[[services.ports.http]]
paths = ["/"]
